Don't #undef UMA_HISTOGRAM_UNUSED
Oops, can't undef the UNUSED macro because it's not expanded until
the top level macro's usage site.

i.e.

d:\src\crashpad\crashpad\util\misc\metrics.cc(24) : error C3861: 'UMA_HISTOGRAM_UNUSED': identifier not found

R=mark@chromium.org
BUG=crashpad:100

Change-Id: Ia14eb97706cffc81c565f12e5b5ef5a843517372