mini_chromium: Respect CC/CXX if set
I was getting this on Linux builds:

clang++ -MMD -MF obj/snapshot/elf/snapshot.elf_image_reader.o.d -D_FILE_OFFSET_BITS=64 -I../.. -I../../compat/linux -I../../compat/non_win -I../../third_party/mini_chromium/mini_chromium -Wall -Wendif-labels -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wsign-compare -fno-exceptions -fno-rtti -fno-strict-aliasing -fobjc-call-cxx-cdtors -fstack-protector-all -fvisibility-inlines-hidden -fvisibility=hidden -Wheader-hygiene -Wnewline-eof -Wstring-conversion -fPIC -Wimplicit-fallthrough -pthread -Wexit-time-destructors -std=c++14 -c ../../snapshot/elf/elf_image_reader.cc -o obj/snapshot/elf/snapshot.elf_image_reader.o
../../snapshot/elf/elf_image_reader.cc:250:51: error: invalid use of non-static data member 'n_namesz'
  static_assert(sizeof(*type) >= sizeof(NhdrType::n_namesz),
                                        ~~~~~~~~~~^~~~~~~~
../../snapshot/elf/elf_image_reader.cc:213:34: note: in instantiation of function template specialization 'crashpad::ElfImageReader::NoteReader::ReadNote<Elf64_Nhdr>' requested here
    result = range_->Is64Bit() ? ReadNote<Elf64_Nhdr>(name, type, desc)
                                 ^
../../snapshot/elf/elf_image_reader.cc:250:51: error: invalid use of non-static data member 'n_namesz'
  static_assert(sizeof(*type) >= sizeof(NhdrType::n_namesz),
                                        ~~~~~~~~~~^~~~~~~~
../../snapshot/elf/elf_image_reader.cc:214:34: note: in instantiation of function template specialization 'crashpad::ElfImageReader::NoteReader::ReadNote<Elf32_Nhdr>' requested here
                               : ReadNote<Elf32_Nhdr>(name, type, desc);
                                 ^
2 errors generated.

I thought it was due to header differences since it wasn't happening on
Fuchsia, but after some confusion realized it was because the standard
clang on Ubuntu is only 3.9, but taking a sizeof a non-static member
apparently wasn't implemented back then. With flags otherwise unchanged,
it works with
5.0.1 from releases.llvm.org.

Likely, we should just make a temporary variable to static_assert with
there, but supporting CC/CXX seems like a reasonable idea too.

Change-Id: Ie74152234500bf963047cca59cc5f991712b1f4a