Update patch set 4
Patch Set 4:

There are a bunch of other errors that I get once I fix this one. Another example:

CompileC /Users/msarda/Library/Developer/Xcode/DerivedData/SmartLock_osx-gztfuyjdiytwblauiunzsuwnpzdc/Build/Intermediates/snapshot_osx.build/Debug/crashpad_snapshot.build/Objects-normal/x86_64/exception_snapshot_mac.o mac/exception_snapshot_mac.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/msarda/Development/piper_crashpad/google3/third_party/crashpad/crashpad/snapshot
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c++11 -Wno-trigraphs -fno-exceptions -fno-rtti -O0 -Werror -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wshorten-64-to-32 -Wnewline-eof -Wno-c++11-extensions -D_GLIBCXX_DEBUG_PEDANTIC -D_GLIBCXX_DEBUG -D_GLIBCPP_CONCEPT_CHECKS -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fstrict-aliasing -fprofile-arcs -ftest-coverage -Wdeprecated-declarations -Winvalid-offsetof -mmacosx-version-min=10.10 -g -fvisibility=hidden -fvisibility-inlines-hidden -fno-threadsafe-statics -Wno-sign-conversion -I/Users/msarda/Library/Developer/Xcode/DerivedData/SmartLock_osx-gztfuyjdiytwblauiunzsuwnpzdc/Build/Products/Debug/include -I../../../.. -I.. -I../compat/mac -I../compat/non_cxx11_lib -I../compat/non_win -I../../../mini_chromium/mini_chromium -I/Users/msarda/Library/Developer/Xcode/DerivedData/SmartLock_osx-gztfuyjdiytwblauiunzsuwnpzdc/Build/Intermediates/snapshot_osx.build/Debug/crashpad_snapshot.build/DerivedSources/x86_64 -I/Users/msarda/Library/Developer/Xcode/DerivedData/SmartLock_osx-gztfuyjdiytwblauiunzsuwnpzdc/Build/Intermediates/snapshot_osx.build/Debug/crashpad_snapshot.build/DerivedSources -Wall -Wendif-labels -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wexit-time-destructors -Wheader-hygiene -Wno-selector-type-mismatch -Wsign-compare -Wstring-conversion -Wall -Wextra -Wendif-labels -Wnewline-eof -Wno-unused-parameter -Wno-missing-field-initializers -F/Users/msarda/Library/Developer/Xcode/DerivedData/SmartLock_osx-gztfuyjdiytwblauiunzsuwnpzdc/Build/Products/Debug -std=c++11 -stdlib=libc++ -MMD -MT dependencies -MF /Users/msarda/Library/Developer/Xcode/DerivedData/SmartLock_osx-gztfuyjdiytwblauiunzsuwnpzdc/Build/Intermediates/snapshot_osx.build/Debug/crashpad_snapshot.build/Objects-normal/x86_64/exception_snapshot_mac.d --serialize-diagnostics /Users/msarda/Library/Developer/Xcode/DerivedData/SmartLock_osx-gztfuyjdiytwblauiunzsuwnpzdc/Build/Intermediates/snapshot_osx.build/Debug/crashpad_snapshot.build/Objects-normal/x86_64/exception_snapshot_mac.dia -c /Users/msarda/Development/piper_crashpad/google3/third_party/crashpad/crashpad/snapshot/mac/exception_snapshot_mac.cc -o /Users/msarda/Library/Developer/Xcode/DerivedData/SmartLock_osx-gztfuyjdiytwblauiunzsuwnpzdc/Build/Intermediates/snapshot_osx.build/Debug/crashpad_snapshot.build/Objects-normal/x86_64/exception_snapshot_mac.o

/Users/msarda/Development/piper_crashpad/google3/third_party/crashpad/crashpad/snapshot/mac/exception_snapshot_mac.cc:139:25: error: implicit conversion loses integer precision: 'const uint64_t' (aka 'const unsigned long long') to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
    exception_code_0_ = unsigned_exception_code_0;
                      ~ ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Patch-set: 4